### ISSUE TITLE
组件里面使用了touch指令后,该组件如果应用在多处,只在一个页面其作用

### ISSUE THREAD

**Issue by pronebel** [lenvonsam/vue2-touch#1]
PS:好吧,以为你是老外的,憋了好一会英文,写的也不顺.到你首页看看.个人网站是cn的 ^_^

组件里面使用了touch指令后,该组件如果应用在多处,只在一个页面其作用.

我自己改了这里,后使用正常,从原来的代码看,evt,在一个组件里面被共享了
调试发现, unbind.会在新的页面中的相同的苏件的unbind之后才执行.所以导致新的实例,总是bind不到事件.

我自己本地作了如下改动后,解决了问题.你看你的代码采用什么方式解决下 ^_^

  bind: function(el, binding) {
  var handler = null;
    var evtType = '';
    if (!el.evt) {
      el.evt = new Hammer.Manager(el)
    }
    let evt = el.evt;

.....
}

 unbind: function(el) {
    el.evt.destroy()
    el.evt = null
  }

**Comment by Jiiiiiin** [comment]
@pronebel 因为我没有看插件源码没有评论权，目前暂时没有使用了，看了Minu-ui源码示例，他们使用的是：
```
document.addEventListener('DOMContentLoaded', function() {
  if (window.FastClick) window.FastClick.attach(document.body);
}, false);
```

目前还没有进行ui测试，不知道几个东西之间的优劣。

**Comment by pronebel** [comment]
你列的代码和这个不一样的哦.这个是基于Hammer.js的封装
