### ISSUE TITLE
多个事件绑定bug！

### ISSUE THREAD

**Issue by Jiiiiiin** [lenvonsam/vue2-touch#2]
` <div class="flex-left but-box">
        <div class="unit btn-mobile">
          <mt-button type="default" class="btn" @click="onMobileTap">手机版</mt-button>
        </div>
        <div class="unit">
          <mt-button type="primary" class="btn" @click="onPadTap">Pad版</mt-button>
        </div>
      </div>
    </div>
`

如果上面两个点击事件换成tap事件，出现点击手机btn执行Pad btn绑定的事件！！！

**Comment by pronebel** [comment]
这个我猜就是因为代码李的变量共享的问题,
参考这个  https://github.com/lenvonsam/vue2-touch/issues/1
作更改之后试下

**Comment by lenvonsam** [comment]
先只支持单个事件绑定
