### ISSUE TITLE
swipe works, but swipeleft and swiperight don't

### ISSUE THREAD

**Issue by mkastner** [lenvonsam/vue2-touch#6]
this works

v-touch:swipe="swipeCB"

but with

v-touch:swipeleft="swipeLeftCB"

v-touch:swiperight="swipeRightCB"

The error message says:

[Warning] [vue2-touch] event type value is invalid (vendor.js, line 30975)

**Comment by Felwin** [comment]
You have to use only `v-touch:swipe` the direction ('swipeleft' or 'swiperight') is the first argument passed to the callback.
`v-touch:swipe="callback"`
`callback (direction) { console.log(direction) }`

**Comment by lenvonsam** [comment]
@mkastner Felwin's answer is correct, you'd better to use touch plugin with that way
